env:
    DEVICE_CODENAME: lavender
    BUILD_USER: CAF
    BUILD_HOST: zenitsuprjkt
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[114fd2aa84cd8dca6e52610342e7225ffc28be9fda4dd2cb1ff46df976e3bf9319a31fa37af7614e9f7e246e43a9d971]"
    TG_TOKEN: "ENCRYPTED[e063ad26221d3a5c3bae7a2af27d6765013cf448f437a2736fff97376d93882026b0b5a64479797e73ff1a65ccecfb9b]"
    TG_CHAT_ID: "ENCRYPTED[86c6f7f21b00aaba8eb88c4e7b51a03cb1a4d6b258b2c0b14b2f77fbc321dc48ff21b5a17ba3d0940b65ac80d84cc0de]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: zenitsuprjkt/docker:latest
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env

  Spec-Check_script:
      - ./disk.sh
  
  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
#      - ./clang.sh
#      - ./rm.sh

  Build_kernel_GCC_script:
     - ./gcc.sh
     - ./rm.sh

  Notif_script:
      - ./done.sh
