env:
    DEVICE_CODENAME: lavender
    BUILD_USER: CAF
    BUILD_HOST: zenitsuprjkt
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "ENCRYPTED[25fe654288f7082486c60ec86c7f2947d0e6397e3406d4b04fc46b158c9d2b49ac35694c1d407b826aca1c0fcf3c2803]"
    TG_TOKEN: "ENCRYPTED[f80e58b25f8ab8dcdc460a1f0f8abd8d65936b7c99c7bceacc3ee18d624c9629a1e012bc0d495a89a308dc36932cd49d]"
    TG_CHAT_ID: "ENCRYPTED[86c6f7f21b00aaba8eb88c4e7b51a03cb1a4d6b258b2c0b14b2f77fbc321dc48ff21b5a17ba3d0940b65ac80d84cc0de]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Environment_script:
      - cat /etc/os*
      - env

  Spec-Check_script:
      - ./disk.sh
  
  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./rm.sh

  Build_kernel_GCC_script:
     - ./gcc.sh
     - ./rm.sh

  Notif_script:
#      - ./done.sh
